### PR TITLE
nfsserver: systemd tests to make sure all services are running and monitored

### PR DESCRIPTION
**Pull request by oalbrigt**

### CODE REVIEW

**Comment by krig** [comment]
Hmm, I don't think this will work as-is on SUSE systems, IIRC rpcbind is handled differently. I'll look into it.

**Comment by oalbrigt** [comment]
Sure. Any suggestions for improvements are welcome.

**Comment by krig** [comment]
I'll get back to you soon.

**Comment by ytakeshita** [comment]
Great patch ! Thank you !

this while loop doesn't finish until resources's timeout (op start) although there is the counter i .
Is it as intended ?
```
+	case $EXEC_MODE in
+            [23]) nfs_exec start rpcbind
+		  local i=1
+		  while : ; do
+			ocf_log info "Start: rpcbind i: $i"
+			rpcinfo > /dev/null 2>&1
+			rc=$?
+			if [ "$rc" -eq "0" ]; then
+				break;
+			fi
+			sleep 1
+			i=$((i + 1))
+		  done
+		  ;;
+	esac
```

**Comment by oalbrigt** [comment]
That is to be able to see easily if it is stuck waiting for a specific service, and that we might want to change (or remove) in the future.

**Comment by ytakeshita** [comment]
OK. I see.

**Comment by krig** [comment]
@oalbrigt I've checked, and I think this should work fine on SUSE as well. Merging this looks good to me. :+1:

**Comment by oalbrigt** [comment]
Great. Thanks for checking.

**Pull request merged**
