### PR TITLE
Container-monitoring resources

### PR DESCRIPTION
**Pull request by mgrzybek**
This PR adds two RA :
* LXDInfo : retrieves the number of running LXD containers  using `lxc list` and updates the CRM attributes
* MachineInfo : retrieves the number of running systemd machines using `machinectl` and updates the CRM attributes

### CODE REVIEW

**Comment by krig** [comment]
`LXDInfo` doesn't have the executable bit set, that's why the CI check fails.

**Comment by krig** [comment]
Ah, right: Please add the new agents to `doc/man/Makefile.am` as well, to generate the man pages.

**Comment by krig** [comment]
Great, thanks!

**Comment by krig** [comment]
Oh, I forgot about the naming policy we're trying to enforce. Would it be OK with you if we rename these agents `lxd-info` and `machine-info`?

**Comment by mgrzybek** [comment]
That's all right.
Is there any document related to the naming convention?

**Comment by krig** [comment]
There isn't yet. The convention-to-be is "lowercase with optional -'s".

**Pull request merged**
