### PR TITLE
Dummy RA in Python

### PR DESCRIPTION
**Pull request by yandroskaos**
Mimicking the behaviour of the shell Dummy RA, a dummy RA wirtten in Python is provided as example.

### CODE REVIEW

**Comment by oalbrigt** [comment]
Please only change indentation where it's inconsistant, so patches are easy to apply/review for distros instead of being a full replacement of the code.

**Comment by oalbrigt** [comment]
Nevermind. I thought it ws the other PR.

**Comment by oalbrigt** [comment]
ok to test

**Comment by oalbrigt** [comment]
LGTM.

**Comment by oalbrigt** [comment]
Thanks.

**Comment by oalbrigt** [comment]
I've made it Python 2.x compatible, so it passes our CI:
https://github.com/ClusterLabs/resource-agents/pull/1521

Can you check if I've interpreted line 97 correctly?

**Comment by yandroskaos** [comment]
Nice!
Regarding line 97, looks good to me. Original $$ name was obtained by dummy bash version, and looks like validation was only to check being able to write in the containing directory.

**Comment by oalbrigt** [comment]
Ah. So either way is fine then. I'll merge it.

Thanks for your prompt reponse.

**Pull request merged**
