### PR TITLE
Medium: SAPInstance: Add IS_ERS parameter (bsc#1036486)

### PR DESCRIPTION
**Pull request by krig**
* `IS_ERS`

If `IS_ERS` is true, mark a per cluster attribute for a
specific ASCS/ERS pair describing which node is the
best place to failover a failed ASCS.

### CODE REVIEW

**Comment by oalbrigt** [comment]
The AUTOMATIC_UNMIGRATE should be available in client utilities, and not in resource agents (available as e.g. "pcs resource move <resource> [lifetime=<lifetime>]").

From "pcs resource move" usage info:
If lifetime is specified then the constraint will expire after that time, otherwise it defaults to infinity and the constraint can be cleared manually with 'pcs resource clear' or 'pcs constraint delete'.

**Comment by krig** [comment]
Constraint lifetimes isn't a popular alternative since the constraint will remain in the configuration indefinitely, confusing people. Maybe scheduling a regular cleanup of such constraints could be an option...

**Comment by krig** [comment]
@oalbrigt We decided to drop the second parameter and follow the alternative approach of constraint lifetime + scheduled cleanup of the CIB.

**Comment by oalbrigt** [comment]
@krig: Great. Looks good to me.

**Comment by krig** [comment]
Great. Will wait for a decision from the SAP developers before merging.

**Comment by krig** [comment]
Merging based on request from Fabian (and the positive feedback so far).

**Pull request merged**
