### PR TITLE
[openstack agents] Volume re-attaching, v3 API, get hostname from corosync

### PR DESCRIPTION
**Pull request by mgrzybek**
This PR:
* provides a better layout
* uses crm_node -n result instead of $HOSTNAME
* deals with API v3 (tenant / project)

I had some rebase problems (#1198). I have recreated the PR.

### CODE REVIEW

**Comment by krig** [comment]
Hi @mgrzybek, in the developers mailing list @aspiers pointed out that there are existing resource agents for openstack at https://git.openstack.org/cgit/openstack/openstack-resource-agents and that the processes for openstack make hosting the agents in this repository difficult.

In order to avoid a potentially confusing situation, is there a possibility for the two of you to collaborate on a single set of agents?

**Comment by mgrzybek** [comment]
Hi @krig 
That's sounds fine to me. I'm sending an email.
Mathieu

**Comment by krig** [comment]
@mgrzybek Thank you!

**Comment by mgrzybek** [comment]
Hi @krig !

Do you have news about the way to deal with openstack agents?
I have some coming patches.

Mathieu

**Comment by oalbrigt** [comment]
There's some issue with one of the CI's today, so just ignore it's status for now.

**Comment by fabbione** [comment]
test this please

**Comment by fabbione** [comment]
test this please

**Comment by mgrzybek** [comment]
For now nothing to commit. The last build is still in progress.

**Pull request merged**
