### PR TITLE
Add systemctl resource agent to manage systemd services.

### PR DESCRIPTION
**Pull request by sebastic**
An alternative to LSB resource agents.

We're using it at $DAYJOB for about a year now.

### CODE REVIEW

**Comment by oalbrigt** [comment]
Pacemaker supports running systemd services as "agents", so what's the point in using this agent instead?

**Comment by sebastic** [comment]
It's an alternative.

I developed it back then because I didn't find documentation how to use systemd services with pacemaker.

That documentation is still hard to find.

**Comment by oalbrigt** [comment]
@kgaillot Sounds like we should consider making the systemd documentation easier to find (and maybe mention it where appropriate).

**Comment by kpfleming** [comment]
Agreed! I'm using the systemd RA and it works fine, but there is literally zero documentation available for it.

**Comment by kgaillot** [comment]
There's a brief mention in "Pacemaker Explained", but it could definitely be improved.

**Pull request closed without merging**
