### PR TITLE
Medium: aws-vpc-route53: Fix tempfile race (bsc#1059312)

### PR DESCRIPTION
**Pull request by krig**

### CODE REVIEW

**Comment by dmuhamedagic** [comment]
The second commit is a mix of some refactoring and, I guess,
the actual fix. But I find it really difficult to follow. Any
chance of splitting this into self-contained changes?

**Comment by krig** [comment]
Hmm yeah, I combined all the places that were writing the file into a single function. I'll see if I can split it in a clearer way.

**Comment by dmuhamedagic** [comment]
Yes, that's definitely an improvement, it's just that I couldn't
pinpoint the actual fix ;-)

**Comment by krig** [comment]
Understandable :)

**Comment by krig** [comment]
Updated and split into three commits: The actual fix, the duplication cleanup and the logging cleanup.

**Comment by dmuhamedagic** [comment]
Great! I'll take a look at it tomorrow.

**Comment by dmuhamedagic** [comment]
Thanks!

**Comment by krig** [comment]
Thank you!

**Pull request merged**
