### PR TITLE
CTDB: replace timeout override w/ctdb_timeout parameter

### PR DESCRIPTION
**Pull request by dev-ddoe**
Timelimit is enough to manage resource timeoutin CTDB module
#1660

### CODE REVIEW

**Comment by oalbrigt** [comment]
We probably want to set it to a specific value to avoid any issues if the default is different in different versions of CTDB.

I'm waiting for feedback from our CTDB devs about which value we should use.

**Comment by obnoxxx** [comment]
I tend to agree that 

* having an explicit default value here
* and still having a way to override it 

might be better.

What I don't quite understand from the original code is that both the timeout and the timelimit are overridden with the same value.

**Comment by oalbrigt** [comment]
That was probably just a mistake, when they tried to set it based on the timeout value of the action:
https://github.com/ClusterLabs/resource-agents/commit/7bd548c0088224d8c99c1ebb1289cc931a9ec598

**Comment by oalbrigt** [comment]
Sounds good. I guess we could add it as a parameter, and have it default to 10.

**Comment by oalbrigt** [comment]
ok to test

**Comment by oalbrigt** [comment]
Thanks.

**Pull request merged**
