### PR TITLE
Update heartbeat/pgsql

### PR DESCRIPTION
**Pull request by dbk-rabel**
#1706

### CODE REVIEW

**Comment by HideoYamauchi** [comment]
Hi dbk-rabel,

Perhaps it has been discussed in the issue or PR before, but the LOCK file should only be deleted when a single Master stops.
So I think the current code is correct.

Best Regards,
Hideo Yamauchi.

**Comment by dbk-rabel** [comment]
Hi HideoYamauchi,

thanks a lot for your answer!

But I don't seem to understand that. When the master shuts down and there are still Slaves to take over, it should be safe to remove the LOCK file, so the master can start again later. Even more, if the master is not even stopped, but just demoted to slave, while another slave takes over the master role.

It seems, I got something wrong here, but I'm not able to figure it out. It would be very helpful, if you could explain to me in more detail.

The background for me is actually: How to safely reboot the master node, without any manual interaction?

Yours
  David

**Comment by HideoYamauchi** [comment]
Hi dbk-rabel,

The discussion of the next issue may be helpful to you.
 - https://github.com/ClusterLabs/resource-agents/issues/808

Best Regards,
Hideo Yamauchi.

**Comment by dbk-rabel** [comment]
Yes, that helped. Thank you!

**Pull request closed without merging**
