### PR TITLE
ldirectord.in: dns_check and fallbackcommand enhancements

### PR DESCRIPTION
**Pull request by MorphBonehunter**
- support for custom dns ports
- dns check results are now regex ready
- fallback cmd arguments added

### CODE REVIEW

**Comment by dmuhamedagic** [comment]
@horms, could you take a look at this one please. Thanks!

**Comment by MorphBonehunter** [comment]
We have rebased on clusterlabs master and append 2 commits with documentation and explanation of the functionality we have added.
With the rebase the comments from @horms got lost (first time i did such an thing on github, so maybe i did this wrong), sorry.

**Comment by MorphBonehunter** [comment]
I "restore" the lost comments.
We "fix" only the DNS Check as we have an use case for this, we do not check other protocols so we can not make a statement how many other protocol checks don't honor the port configuration.

**Comment by MorphBonehunter** [comment]
With the hint from @horms we check all the other "check_" subs and find all honor the port configuration.
With this task we discover that there is an sub for the port check which is unsed by the other checks, so we adjust our commit to unify the code.

**Comment by horms** [comment]
@MorphBonehunter: Thanks. I'm happy with this series now.
@dmuhamedagic: please feel free to apply

**Comment by dmuhamedagic** [comment]
Thanks!

**Pull request merged**
