### PR TITLE
LinuxSCSI:replace error log messages with calls to ocf_exit_reason

### PR DESCRIPTION
**Pull request by WangMengabc**
issue #704
LinuxSCSI RA update ocf_exit_reason support

### CODE REVIEW

**Comment by wenningerk** [comment]
test this please

**Comment by wenningerk** [comment]
looks as if I've lost my caps on this repo :-(

**Comment by oalbrigt** [comment]
ok to test

**Comment by oalbrigt** [comment]
LGTM. Thanks.

**Pull request merged**
