### PR TITLE
Make secure tmp files

### PR DESCRIPTION
**Pull request by varkoly**
There are various problems with tmp-races. Some of them may be used for LPE.
This changes makes resource-agents safer.

### CODE REVIEW

**Comment by varkoly** [comment]
Fixes the issue: https://github.com/ClusterLabs/resource-agents/issues/1049

**Comment by oalbrigt** [comment]
ok to test

**Comment by oalbrigt** [comment]
LGTM. @fdanapfel can you see if you're fine with these changes for the SAP agents?

**Comment by diegoakechi** [comment]
@fmherschel You might want to take a look here too...

**Comment by fmherschel** [comment]
> @fmherschel You might want to take a look here too...

The only thing I am wondering about is why parts of the patch are moving the temporary files from /tmp to (literal) "/var/run" while others are using the OCF reference "${HA_RSCTMP}".
Is that difference implemented by intention?

**Comment by fdanapfel** [comment]
@oalbrigt The changes for the SAP agent look OK to me.

@fmherschel: looks to me like the second commit fixes this so that "${HA_RSCTMP}" is used instead of /var/un in all places

**Comment by oalbrigt** [comment]
> > @fmherschel You might want to take a look here too...
> 
> The only thing I am wondering about is why parts of the patch are moving the temporary files from /tmp to (literal) "/var/run" while others are using the OCF reference "${HA_RSCTMP}".
> Is that difference implemented by intention?

That seems to be a mistake in the first commit, that he fixes in the 2nd commit. If you check Files Changed in the PR you'll see no reference to "/var/...".

**Pull request merged**
