### PR TITLE
azure-lb: set socat to default on SUSE distributions.

### PR DESCRIPTION
**Pull request by varkoly**
Socat was tested on SUSE and it works fine. To avoid the need to change the configuration we set socat to default on SUSE distributions.

### CODE REVIEW

**Comment by oalbrigt** [comment]
ok to test

**Comment by oalbrigt** [comment]
Can you update the commit message with prefix "azure-lb:"? So it's clear from the commit log which agent it's updating.

**Comment by varkoly** [comment]
> Can you update the commit message with prefix "azure-lb:"? So it's clear from the commit log which agent it's updating.
Changed.

**Comment by diegoakechi** [comment]
@varkoly please, rebase your branch and squash this change into a single commit with the right title.

**Comment by varkoly** [comment]
will create new PR

**Pull request closed without merging**
