### PR TITLE
New RA that manages IP moving in GCP

### PR DESCRIPTION
**Pull request by dud225**
Hello

This Resource Agent uses the GCP API to move a floating IP addresse within a GCP VPC by changing an entry in the routing table, as discussed in the [documentation](https://cloud.google.com/solutions/best-practices-floating-ip-addresses#option_4_failover_using_routes_api_calls).

This agent also configures the floating IP locally on the instance OS.

### CODE REVIEW

**Comment by oalbrigt** [comment]
Wouldnt it be better to use IPaddr2 for the ip-functionality, and only use the ip command where it's necessary for checks?

**Comment by dud225** [comment]
Hello @oalbrigt 

that's a excellent question.
I've tought about it quite some time, here are my arguments : 
- IPaddr2 is more suited to conventional LAN networks where the admin manages the whole network. In particular  IPaddr2 regularly sends gratuitous ARPs to the others nodes but these frames are completely [ignored in GPG](https://cloud.google.com/solutions/best-practices-floating-ip-addresses#challenges_with_migrating_floating_ips_to_compute_engine)
- this code is based on the rival RA aws-vpc-move-ip that is also managing the IP itself. I've asked the original commiter @krig the same question, but I haven't received any feedback yet.

Regards
dud

**Comment by krig** [comment]
@dud225 @oalbrigt Ah yes, I meant to reply to that, thanks for reminding me :) I'm not the original author so I can't speak to the motivation for why it doesn't rely on IPaddr/IPaddr2 for the actual IP management. I just assumed it was due to AWS-specific needs...

**Comment by kskmori** [comment]
From my experience of AWS, though I'm not the original author of aws-vpc-move-ip but I've developed a similar RA on AWS before, it is necessary to use routing tables because a virtual IP cannot migrate across Availability Zones since they must have different subnets on AWS. (I heard that it is called the routing based HA cloud design pattern, but can not find a good reference right now)

The situation seems quite different on GCP according to the document above, but I feel like that it is a good thing to follow what the official documents tell you to do so.

Just my two cents.

**Comment by oalbrigt** [comment]
Sounds good to me.

**Comment by dud225** [comment]
> so I can't speak to the motivation for why it doesn't rely on IPaddr/IPaddr2 for the actual IP management. I just assumed it was due to AWS-specific needs...

Although I haven't tested it, I don't think there any constraints from either AWS or GCP preventing the use of IPaddr2, it's just that the ARP frames will be ignored.

AFAIU the others AWS RA work differently : 
- awseip : AWS automatically enforces NAT that translates the EIP to the private IP, so that this is transparent to the instance
- awsvip : the instance needs to have the secondary IP locally configured but fortunately as from the [doc](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/MultipleIP.html#StepTwoConfigOS)  there is a package that takes care all of it. On Debian this package doesn't exist but the Debian team that manages the official Debian AMI includes the [needed files inside each AMI](https://wiki.debian.org/Cloud/AmazonEC2Image/Jessie). So IPaddr2 may not be needed if there is another mechanism already present

So the whole point to my decision is to avoid unneeded stuff and to make things easier to configure ( I admit that this last point is kind of a weak argument).

**Pull request merged**
