### PR TITLE
Load apache status modules from RA cmdline for SUSE only OS

### PR DESCRIPTION
**Pull request by MalloZup**
Load apache status modules from RA cmdline for SUSE only OS

### CODE REVIEW

**Comment by krig** [comment]
I think this looks good to me, but maybe @oalbrigt wants to have look as well. Could this cause issues for someone who wants to implement their own status API and not use `mod_status`, though? At least in theory, I could imagine that there are existing users who don't use `mod_status`..

**Comment by MalloZup** [comment]
@krig  right. I have added an additional check for last comment. Thx for comments :couch_and_lamp: :+1:

**Comment by oalbrigt** [comment]
ok to test

**Comment by oalbrigt** [comment]
LGTM

**Comment by MalloZup** [comment]
5hf @krig feel fre to merge

**Pull request merged**
