### PR TITLE
ldirectord: Correctly suppress startup e-mails when emailalertstatus=running

### PR DESCRIPTION
**Pull request by mcnewton**
When the daemon is starting up it sets DAEMON_STATUS to STARTING, aligns its internal tables with those of ipvsadm (in ld_start), then sets DAEMON_STATUS to RUNNING.

This means that any services which are down (which is usually the case when ldirectord is not running, unless cleanstop=no is set) will be marked as down in STARTING state.

Then when the main loop in ld_main is run, the services will all be detected as 'up', but as we are now in RUNNING state, so e-mails will be sent out. This isn't really a running state, though - we've only just started up.

To prevent this from happening, do a one off initial check of all real servers in the ld_start, which means that services will be detected as 'up' when in DAEMON_STATUS STARTING. From then on the ld_main (or the children in fork=yes mode) will continue to check as usual and send e-mails out if applicable in RUNNING state.

In the other case, where emailalertstatus=starting, similarly now the startup e-mails will be sent, whereas previously e-mails would be sent to say the service is down, but not any to say that the servers were actually up and running.

### CODE REVIEW

**Comment by krig** [comment]
This change look reasonable to me, and apologies for being troublesome, but could you tag each commit message with `ldirectord:`? With that change, I'll merge.

**Comment by mcnewton** [comment]
@krig no problem! Hope it's OK now?

**Comment by krig** [comment]
Great, thanks!

**Comment by mcnewton** [comment]
Thanks!

**Pull request merged**
