### PR TITLE
send_arp: update usage info

### PR DESCRIPTION
**Pull request by oalbrigt**
I havent had the chance to test the libnet version, so please test that it's working fine as well.

### CODE REVIEW

**Comment by lge** [comment]
While at it, do you intend to do all of this (see https://github.com/ClusterLabs/resource-agents/pull/654#issuecomment-128015953)?

> We may consider changing send_arp.libnet.c calling conventions to match those of iputils arping instead, drop the ipoibarping special case from IPaddr2, change the calling convention in IPaddr2, and possibly add an optional preference on the platform arping over our own send_arp.
> Then deprecate send_arp and at some point just depend on iputils being installed and working.

**Comment by kskmori** [comment]
I have been working on another approach to address all of those issues related to send_arp on my private repo. at https://github.com/kskmori/resource-agents/issues/6 .

The basic approach of mine is that:
 - allow to choose arping command instead of send_arp binary by a parameter, so it could be a default in the future.
 - keep the send_arp code untouched as much as possible to keep the backward compatibility easier with minimal efforts

It is almost done but I am still working on it for some issues.
I will post a pull request soon after I have finished it, so that we can discuss what is the best way.

**Comment by oalbrigt** [comment]
@kskmori: sounds good. I have copied the old code to .old.c-files in case someone still need it.

**Comment by kskmori** [comment]
This is fixed in a way as #977 .

**Pull request closed without merging**
