### PR TITLE
Nagios Resource Agent

### PR DESCRIPTION
**Pull request by oalbrigt**
Cleaned up version of: https://github.com/ClusterLabs/resource-agents/pull/636

Any suggestions for improvements are welcome.

### CODE REVIEW

**Comment by oalbrigt** [comment]
Thank you for your feedback. I've tried to fix all the issues you mentioned.

**Comment by oalbrigt** [comment]
The "command" file can be generated by other applications with commands that Nagios will run periodically:
https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/extcommands.html

**Comment by dmuhamedagic** [comment]
On Wed, Dec 02, 2015 at 06:16:01AM -0800, oalbrigt wrote:
> The "command" file can be generated by other applications with commands that Nagios will run periodically:
> https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/extcommands.html

But how do we know that it's going to be there when we need it
and, in particular, when we remove it after every start?

**Comment by oalbrigt** [comment]
I guess it's only used for commands that needs to be run while it's running like to trigger a reload or similar features, as it's removed during start in the init-script in RHEL7 that I used as a reference when going through the code.

**Comment by dmuhamedagic** [comment]
Looks fine to me.
Did you also test using ocf-tester?
Care to rebase to a single patch?

**Comment by oalbrigt** [comment]
It passed the ocf-tester when I commented out the ocf_is_root part, which made it fail due to the permissions test being done as nobody.

**Comment by dmuhamedagic** [comment]
OK. Thanks!

**Pull request merged**
