### PR TITLE
Medium: Fix issues discovered by Shellcheck

### PR DESCRIPTION
**Pull request by krig**
Series of commits that clean up and fix issues reported by Shellcheck.

With these changes, the `ci/build.sh` succeeds with the current configuration (ignoring info and warning level notifications, and ignoring errors that are less relevant to resource-agents).

### CODE REVIEW

**Comment by dmuhamedagic** [comment]
Quite some work here, pity to just pacify a tool.
Looks good, but unfortunately won't merge anymore (tomcat) :(

**Comment by krig** [comment]
I will update the pull request.

Pacifying the tool has great value in this case: If we can get ShellCheck to accept the current state, we can have it check every pull request, so that simple errors like typos or broken code are caught by the automatic check even before a human has to look at it.

I think it is worth jumping through a few hoops to get automated verification up and running.

**Comment by krig** [comment]
Great! Now I just need a bit more help: I don't have permissions to enable Travis on this repository (I have it enabled on my own fork, but then we don't get the nice integration on each pull request): Someone with ownership rights to this repository has to enable it for the repository. Maybe @kgaillot can help with that part?

**Comment by oalbrigt** [comment]
I have activated Travis for the repository.

**Comment by krig** [comment]
Thanks!

**Pull request merged**
