### PR TITLE
Mid: ocf-shellfuncs: Explicitly specify $OCF_RESOURCE_INSTANCE in the p parameter for compatibility.

### PR DESCRIPTION
**Pull request by HideoYamauchi**
Hi All,

The following fixes were made in pacemaker:
 - https://github.com/ClusterLabs/pacemaker/pull/3039

For compatibility, specify the option specification explicitly.

Best Regards,
Hideo Yamauchi.

### CODE REVIEW

**Comment by oalbrigt** [comment]
I dont think this makes sense. It's up to the agent to specify $OCF_RESOURCE_INSTANCE.

**Comment by oalbrigt** [comment]
I'll ask Ken about it just to be sure I'm not missing the point here.

**Comment by HideoYamauchi** [comment]
Hi Oyvind,

Okay!

----
If you don't have $OCF_RESOURCE_INSTANCE after the p option, you will have problems with some combinations of pacemaker and resource-agent versions.

Or are you saying it's better to specify the p option last?

```
${HA_SBIN_DIR}/crm_attribute $@ -p
```

Best Regards,
Hideo Yamauchi

**Comment by HideoYamauchi** [comment]
> I'll ask Ken about it just to be sure I'm not missing the point here.

All right!

Thanks!
Hideo Yamauchi.

**Comment by oalbrigt** [comment]
Thanks. Ken confirmed this solves the issue for 2.1.0-2.1.5.

**Comment by HideoYamauchi** [comment]
> Thanks. Ken confirmed this solves the issue for 2.1.0-2.1.5.

OKay!

Many thanks,
Hideo Yamauchi.

**Pull request merged**
