### PR TITLE
oralsnr: fix status check fail when username is more than 8 characters long

### PR DESCRIPTION
**Pull request by oalbrigt**

### CODE REVIEW

**Comment by oalbrigt** [comment]
If $ORACLE_OWNER is "oracle123" it will be displayed in `ps -e -o pid,user,args` output as "oracle1+" and the check will fail causing the status check to fail.

**Comment by dmuhamedagic** [comment]
Hmpf. There could be other places where ps -o user | grep $user is used to check for processes.

**Comment by dmuhamedagic** [comment]
Thanks!

**Comment by oalbrigt** [comment]
It seems like that was the only occurence (from a quick grep through the RA's).

**Pull request merged**
