### PR TITLE
[lvmlockd] support lvm2-2.03 which removes lvmetad

### PR DESCRIPTION
**Pull request by zhaohem**
Signed-off-by: Zhao Heming <heming.zhao@suse.com>

### CODE REVIEW

**Comment by zhaohem** [comment]
I have tested.
'!=' would be good enough no mater if "locking_type" or "use_lvmlockd" is assigned or not, empty string or not.

**Comment by oalbrigt** [comment]
ok to test

**Comment by oalbrigt** [comment]
LGTM. Thanks.

**Comment by oalbrigt** [comment]
Additional patch to solve this issue: https://github.com/ClusterLabs/resource-agents/pull/1460

**Pull request merged**
