### PR TITLE
Fix of unnecessary usage of prefx

### PR DESCRIPTION
**Pull request by grueni**

### CODE REVIEW

**Comment by dmuhamedagic** [comment]
@grueni any news here?

**Comment by grueni** [comment]
I am actually very engaged in a new puppet environment. But I will arrange a new pull request today or tomorrow.

Von: Dejan Muhamedagic [mailto:notifications@github.com]
Gesendet: Donnerstag, 8. Januar 2015 14:27
An: ClusterLabs/resource-agents
Cc: Grüninger, Andreas (LGL Extern)
Betreff: Re: [resource-agents] Fix of unnecessary usage of prefx (#515)


@grueni<https://github.com/grueni> any news here?

**Comment by grueni** [comment]
Pull request updated

Von: Dejan Muhamedagic [mailto:notifications@github.com]
Gesendet: Donnerstag, 8. Januar 2015 14:27
An: ClusterLabs/resource-agents
Cc: Grüninger, Andreas (LGL Extern)
Betreff: Re: [resource-agents] Fix of unnecessary usage of prefx (#515)


@grueni<https://github.com/grueni> any news here?

**Comment by dmuhamedagic** [comment]
On Thu, Jan 08, 2015 at 08:48:38AM -0800, grueni wrote:
> Pull request updated

Thanks! I'll test and merge if there are no problems.

**Comment by dmuhamedagic** [comment]
Tested. You didn't actually split the patch, but merging anyway.

**Pull request merged**
