### PR TITLE
Low: docker: simplify image_exists logic

### PR DESCRIPTION
**Pull request by davidvossel**

### CODE REVIEW

**Comment by davidvossel** [comment]
@guessi Does this look right?

**Comment by guessi** [comment]
for testing "-ne 0",
yes, it could be simplified.

actually, it's a typo... oops!

what I really want to commit:

`if [ ${COLON_FOUND} -eq 1 ]; then ...`

"-eq 1", for ensuring there's exactly one "colon" for tagging or nothing
(imply "latest")

but, here I assume that user input is valid.

assigning "repo/image:tag:dummy_tag",
that would be a failure.

so I created #649.

if you (or any contributors) could review that for me, that would be a big
help.

Validation test need carefully process, reviewers needed.

**Comment by dmuhamedagic** [comment]
Has this been fixed in the other pull request (#668)? Can we close it?

**Comment by guessi** [comment]
Hi @dmuhamedagic ,
for me, yes, it could be close

/cc @davidvossel

**Comment by dmuhamedagic** [comment]
Thanks! Closing.

**Pull request closed without merging**
