### PR TITLE
Added "maxfiles" parameter

### PR DESCRIPTION
**Pull request by xtavras**
Added "maxfiles" parameter for increasing maximum number of open files (ulimit -n) for slapd process, useful for many LDAP connections.

### CODE REVIEW

**Comment by dmuhamedagic** [comment]
This introduces a regression by setting the default maxfiles
limit to 4096. I don't know how serious is that, but just to be
on the safe side I suppose that it would be better to remove the
default and set the limit _only_ if the maxfiles parameter is
set.

Also, the indentation is slightly different from the one already
used in the RA.

**Comment by xtavras** [comment]
Hi @dmuhamedagic, slapd on Debian already has 4096 as hard limit, but  it's a good point and I agree with you, I've removed default value and fixed some syntax.

**Comment by dmuhamedagic** [comment]
Yes, well, the ulimit could be set differently by other means.

Thanks for the contribution!

**Comment by dmuhamedagic** [comment]
Fixed meta-data, rebased, pushed. Closing.

**Pull request closed without merging**
