### PR TITLE
Send gratuitous ARP packets during IPaddr2 monitor action

### PR DESCRIPTION
**Pull request by aieri**
This commit introduces a new parameter:
arp_count_refresh (default: 0)

This parameter allows to specify whether to send gratuitous ARP packets during
the monitoring of the resource, and how many.
This is to alleviate issues with potentially stuck switch ARP caches,
which can arise in case of split brain situations. Example:
- a two node cluster is connected directly and also to a switch. Node A
  is master, node B is slave
- communication between master and slave is severed (split brain)
- node B initializes the virtual IPs and sends gratuitous ARP packets
- the switch updated its ARP table to point to B
- node B dies (without node A noticing)
- node A never notices anything wrong

Also, cleaned up mixed indentation.

### CODE REVIEW

**Comment by aieri** [comment]
TODO: update the man page for IPaddr2. I could not find where those are pulled from...

**Comment by oalbrigt** [comment]
Can you update the indentation to use tabs like the rest of the code?

The man page is generated automatically from the meta-data, so you wont have to think about that.

**Comment by dmuhamedagic** [comment]
On Fri, Oct 28, 2016 at 06:51:37AM -0700, Andrea Ieri wrote:
> TODO: update the man page for IPaddr2. I could not find where those are pulled from...

The man pages are produced from the RA meta-data. So, if you
updated the meta-data it should be OK.

**Comment by aieri** [comment]
I have now minimized the diff from the previous version of the file. Please be aware that it isn't actually all tabs, there are a couple of lines that were using mixed indentation (which I have maintained).

**Comment by dmuhamedagic** [comment]
This looks good, but could you please merge related changesets.
Also, please add at the top a short one line description of the form "(Low:|Medium:|High:) IPaddr2: <concise description>". Note that this line is for both users and developers.
Thanks!

**Comment by aieri** [comment]
@dmuhamedagic: by 'merge related changeset' do you mean 'interactive rebase and squash all commits into one, then force push'? And could you elaborate on the "(Low:|Medium:|High:) IPaddr2: "? Sorry, I'm not familiar with the coding style of the project...

**Comment by dmuhamedagic** [comment]
On Wed, Nov 23, 2016 at 01:43:24AM -0800, Andrea Ieri wrote:
> @dmuhamedagic: by 'merge related changeset' do you mean
> 'interactive rebase and squash all commits into one, then force
> push'?

I suppose that you should merge (squash) these three into one:

1b64e69547d567dfab28cc14a314f7179f3fb3a9
516525816a0ef9f27eb8bd3844b28651d0a1defd
98dbd9212fa1ca5e1af4825c340f65a068b94e18

It was quite difficult for me to follow, so maybe we'd have to
revise it again.

In general, fixing mixed indentation is a mixed blessing: the
spacing becomes less annoying, but we loose history.

> And could you elaborate on the "(Low:|Medium:|High:)
> IPaddr2: "? Sorry, I'm not familiar with the coding style of
> the project...

For instance:

Low: IPaddr2: log refresh arp packets at the debug level
Medium: IPaddr2: add option to send refresh arp packets in monitor

**Comment by aieri** [comment]
Done. Thanks for clarifying.

**Comment by dmuhamedagic** [comment]
Thanks!

**Pull request merged**
