### PR TITLE
Medium: nfsserver: fix monitor for systemd

### PR DESCRIPTION
**Pull request by ytakeshita**
instead of PR #741

### CODE REVIEW

**Comment by krig** [comment]
I checked on a SUSE system, and using `/proc/fs/nfsd/threads` should work there as well.

@dmuhamedagic, looks good to you too?

**Comment by oalbrigt** [comment]
Line 307: $rc is not set

And the return codes needs to be updated so it doesnt fail in monitor() when the resource is disabled/not started on the node.

**Comment by ytakeshita** [comment]
> Line 307: $rc is not set

Sorry, it is my mistake. Thank you for pointing out !
fixes in below.
https://github.com/ytakeshita/resource-agents/commit/e7b6c3fbe30e4e8b06d412c402373eb8cd2d9bc3

> And the return codes needs to be updated so it doesnt fail in monitor() when the resource is disabled/not started on the node.

When $rc is not set ? I think if $rc is set correctly, monitor() detect failure in such cases.

**Comment by oalbrigt** [comment]
I tested with setting rc=$? and it still failed.

Also nfs_exec is-active wont work with SysV systems.

FYI. If you commit to fix_nfs_monitor_systemd your fixes will be added here instead of having to link to them.

**Comment by oalbrigt** [comment]
It works fine now. I have no idea why it failed when I changed it myself.

Can you commit the update to this branch and squash it to a single commit?

https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

**Comment by ytakeshita** [comment]
Thanks you for checking and merging !

**Pull request merged**
