### PR TITLE
Low: Rename ra-dev-guide.txt to ra-dev-guide.asc

### PR DESCRIPTION
**Pull request by krig**
Renaming the file enables automatic syntax highlighting.

Fixes: #592

### CODE REVIEW

**Comment by krig** [comment]
Any opinions on this from @oalbrigt or @dmuhamedagic ? Seems safe enough to me.

**Comment by oalbrigt** [comment]
I think we should use the .md extension (as I guess we're using Markdown and not AsciiDoc).

https://github.com/github/markup/blob/master/README.md

**Comment by krig** [comment]
No, the ra-dev-guide is written in Asciidoc. Try converting it to Markdown using a markdown converter and you'll see it won't look very good :)

I guess there's a separate pull request we could make to actually convert it to Markdown instead of Asciidoc, but that would take more than just renaming the file...

**Comment by oalbrigt** [comment]
Then I'm fine with ".asc".

**Comment by krig** [comment]
Alright, thanks! Merging.

**Pull request merged**
