### PR TITLE
syslog-ng: add support for commercial syslog-ng PE

### PR DESCRIPTION
**Pull request by abalage**
Balabit's commercial variant of syslog-ng, a.k.a Premium Edition installs itself into /opt and uses a libexec wrapper to start the actual service, with original path assumption this will not work.
The changes I made strips off the path from the executable (basename). This way it works both with Syslog-NG OSE and PE.

ps. I work for Balabit

### CODE REVIEW

**Comment by oalbrigt** [comment]
You can just set the syslog_ng_binary parameter to the location instead of this patch.

**Comment by abalage** [comment]
I know, but that always means a local change on each system which might be overwritten by any pacemaker package upgrades in the future.

**Comment by oalbrigt** [comment]
No, you set the parameter (for the resource not in the agent), and it'll keep on using it after upgrades.

**Comment by abalage** [comment]
Oh I remember. I tried that. The problem with that is the resource executable which needs to be called is a wrapper script doing environment initialization and doing an exec at the end of the real binary whose path will be different, thus the check logic will not find it within the running processes.

ie. /opt/syslog-ng/sbin/syslog-ng is a symbolic link to /opt/syslog-ng/libexec/syslog-ng-wrapper.sh and the final executable will be /opt/syslog-ng/libexec/syslog-ng and the arguments of course.

What I did was just simply omitting the basedir and leaving syslog-ng <ARGS>.

**Comment by oalbrigt** [comment]
Oh. That makes sense.

**Pull request merged**
