### PR TITLE
Galera - more sh usage

### PR DESCRIPTION
**Pull request by grooverdan**
Bunch of changes to use more sh functions directly.

Also corrected to use --wsrep-new-cluster instead of older empty wsrep_address

### CODE REVIEW

**Comment by grooverdan** [comment]
> If you don't hear anything from me by Jan 8th, ping me on this. The holidays wipe my memory.

ping. glad the memory wipe when well. :-)

**Comment by davidvossel** [comment]
@grooverdan Awesome, I completely forgot. Holiday mission accomplished!

I'll give this test run through this week. Thanks for the reminder.

**Comment by davidvossel** [comment]
@grooverdan alright, testing done. Here's what I found. If I revert the usage of --wsrep-new-cluster, then everything works. Using --wsrep-new-cluster causes the bootstrap node to fail during the promote.

-            extra_opts="--wsrep-new-cluster"
+            extra_opts="--wsrep-cluster-address=gcomm://"

any ideas?

**Comment by dmuhamedagic** [comment]
I'm not sure how much merit there is in replacing pipes of standard unix tools with bash constructs. Do we get the code which is easier to understand and maintain? Was there a need for performance tuning? Is there a performance improvement at all?

**Comment by davidvossel** [comment]
@grooverdan any updates here?

**Comment by grooverdan** [comment]
Not yet sorry. Got a friends server I wanted to try this on to do more thorough testing however he repurposed it. I may get a chance next week.

> I'm not sure how much merit there is in replacing pipes of standard unix tools with bash constructs. Do we get the code which is easier to understand and maintain? Was there a need for performance tuning? Is there a performance improvement at all?

It looks really sloppy for professionals that develop with shell scripts all the time to not use the bash/sh constructs that have been there for a long long time.

For those that don't understand these constructs, like those that have contributed here for years, an easy lookup of the bash/sh man page shows the purpose of these constructs. There might but a performance gain however it wasn't the goal. It was actually to use the shell language to its potential a little bit more. The more times you fork out the more things that can go wrong (oom, process limits, permisssions). So keeping within the shell improves reliability.

**Comment by dmuhamedagic** [comment]
On Tue, Jan 27, 2015 at 03:54:05PM -0800, Daniel Black wrote:
> Not yet sorry. Got a friends server I wanted to try this on to do more thorough testing however he repurposed it. I may get a chance next week.
> 
> > I'm not sure how much merit there is in replacing pipes of standard unix tools with bash constructs. Do we get the code which is easier to understand and maintain? Was there a need for performance tuning? Is there a performance improvement at all?
> 
> It looks really sloppy for professionals that develop with shell scripts all the time to not use the bash/sh constructs that have been there for a long long time.

I respectfully disagree and find that "sloppy" has no place in
your, er, assessment. UNIX philosophy is based on small tools
which do one thing well and which are then combined with pipes to
do more complex stuff. That served me, and some other people,
well for the last 40 or so years. OK, me a bit less than so many
years, but you get the point.

> For those that don't understand these constructs, like those that have contributed here for years, an easy lookup of the bash/sh man page shows the purpose of these constructs. There might but a performance gain however it wasn't the goal. It was actually to use the shell language to its potential a little bit more. The more times you fork out the more things that can go wrong (oom, process limits, permisssions). So keeping within the shell improves reliability.

New code needs to be written, tested for regressions, and then
maintained. Do you think that all that comes for free? If
something is not broken, then why fix it?

**Comment by davidvossel** [comment]
@grooverdan @dmuhamedagic 

Generally, I share Dejan's sentiments here. "If it isn't broken, why fix it?" However for this specific pull request, I actually like all the changes you've made. (except for the one involving that --wsrep-new-cluster option that breaks the agent for me )

Speaking outside of this pull request, some of your changes are technically superior, but produce a larger maintenance burden for those who contribute to the project. This is a reflection of the coding standards this specific project has adopted and not so much what is "technically" right.

**Comment by grooverdan** [comment]
too hostile. bye

**Comment by davidvossel** [comment]
@grooverdan seriously? did you read what I said? What is "hostile" about this discussion? opposed to certain changes, yes. Hostile in how we approached this discussion, no. You've basically just told us you are unwilling to work with us because we are hesitant to introduce some of your changes.

I just said I like what you're doing in this agent and I've been trying to work with you here. we just needed to understand the --wsrep-new-cluster option and why it breaks my deployment. I invested time on this pull request because I value your contribution. However, if criticism is considered "hostile", it might be best to leave this one closed.

**Comment by grooverdan** [comment]
I was bit sensitive before. Sorry. @davidvossel you have put time in to consider these and I appreciate it. @dmuhamedagic "professional" and "sloppy" where poor choices of words - sorry too. I do know some aspects bash better than awk and sed. I guess you consider your yourselves to be representative of your contributor community to know sed and awk better than some of the functions of sh/bash. I'd like to think I applied basic unit testing on the functions changed and I recorded some of these aspects in the PRs even if complete tests of the agents wasn't done.

As mentioned earlier - will try to get to galera next week.

**Comment by dmuhamedagic** [comment]
This doesn't seem to be going anywhere. Please make a new pull request if there's anything more than just style modifications.

**Pull request closed without merging**
