### PR TITLE
IPaddr2 detect duplicate IP

### PR DESCRIPTION
**Pull request by oalbrigt**

### CODE REVIEW

**Comment by krig** [comment]
Could you expand on the commit message a bit more? The `arping` call isn't entirely self-explanatory - at least, I'm not sure how that works reliably.

**Comment by oalbrigt** [comment]
It returns 1 if the IP is in use.

It's basically the same code used in /etc/sysconfig/network-scripts/ifup-eth on RHEL systems.

**Comment by krig** [comment]
I see, thanks!

**Comment by dmuhamedagic** [comment]
This is going to introduce a 4 second wait in the start action. Is the extra check worth it? Shouldn't it be optional? I can vaguely recall people reporting running umpteen (as in hundreds) IP addresses.

Otherwise, we should also add 'check_binary arping'.

**Comment by oalbrigt** [comment]
I've now added a run_arping parameter to be able to disable the check, and it also uses have_binary so it doesnt try to run the check if arping isnt available.

**Comment by dmuhamedagic** [comment]
On Wed, Jan 18, 2017 at 04:36:54AM -0800, Oyvind Albrigtsen wrote:
> I've now added a run_arping parameter to be able to disable the check, and it also uses have_binary so it doesnt try to run the check if arping isnt available.

Great!

But I think that the default should be not to run the check, lest
we surprise people with the delay. It would be a regression of a
kind.

Then, if the run_arping is set to true and arping not available,
the RA should say OCF_ERR_INSTALLED.

**Comment by oalbrigt** [comment]
I've updated it to default to false and check_binary if it's true.

**Pull request merged**
