### PR TITLE
iSCSILogicalUnit: fixes for tgt's rbd (Ceph) backing store

### PR DESCRIPTION
**Pull request by tdb**
These are a couple of fixes to make iSCSILogicalUnit work with tgt's rbd backing store.

### CODE REVIEW

**Comment by krig** [comment]
Could you prefix each commit with `[Medium|Low|High] iSCSILogicalUnit:`?

**Comment by tdb** [comment]
@krig How do I determine if they're low, medium, or high?

**Comment by krig** [comment]
Well, it's a judgement call. If in doubt, go for medium :)

**Comment by tdb** [comment]
@krig does that look better?

**Comment by krig** [comment]
Yes, looks good!

**Pull request merged**
