### PR TITLE
High: clvm: fix issue with only first option of daemon_options being use...

### PR DESCRIPTION
**Pull request by davidvossel**
...d

### CODE REVIEW

**Comment by dmuhamedagic** [comment]
You could also update start_process() to cover this use case too:

start_process()
{
    local binary_path=$1
	shift 1
	local opts=$@
	...

**Comment by davidvossel** [comment]
@dmuhamedagic Good point.  I'm curious, is there any functional difference between the two?

**Comment by lge** [comment]
On Fri, May 15, 2015 at 09:47:17AM -0700, David Vossel wrote:
> @dmuhamedagic Good point.  I'm curious, is there any functional difference between the two? 

Yes.

preserve_args()
{
	local b=$1
	shift
	"$b" "$@"
}

expand_with_word_split()
{
	local b=$1
	local opts=$2
	$b $opts
}

preserve_args "printf" "%4d: %17.17s\n" 1 "some stuff" 2 "other stuff"
   1:        some stuff
   2:       other stuff

expand_with_word_split "printf" "%4d: %17.17s\n 1 some stuff 2 other stuff"
bash: line 12: printf: %17.17s\n: invalid number
bash: line 12: printf: some: invalid number
bash: line 12: printf: stuff: invalid number
bash: line 12: printf: other: invalid number
bash: line 12: printf: stuff: invalid number
   0:   1:   0:   0:   2:   0:   0:

**Comment by davidvossel** [comment]
@lge ah yes, i remember now. we did something similar in a logging function recently.

**Pull request merged**
