### PR TITLE
findif.sh: Use ipcalc tool to generate broadcast address from netmask (#656)

### PR DESCRIPTION
**Pull request by krig**

### CODE REVIEW

**Comment by dmuhamedagic** [comment]
On Tue, Aug 11, 2015 at 02:56:20AM -0700, Kristoffer Grönlund wrote:
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/ClusterLabs/resource-agents/pull/658
> 
> -- Commit Summary --
> 
>   * findif-ipcalc: Add ipcalc tool to be used by findif.sh (#656)

Is there a way to fix this without introducing a new program?
@kskmori, Keisuke-san, you worked on a findif rewrite, any ideas?

**Comment by krig** [comment]
I added the ipcalc tool for performing the broadcast address calculation based on the CIDR netmask. It's not super-complicated, but it's bit-twiddling and I am not confident in my ability to get it right in pure bash. I welcome alternative solutions!

**Comment by krig** [comment]
Sorry, the broadcast address is calculated from the ip and netmask combined: So an address like 192.168.20.4/24 should give the mask 192.168.20.255.

**Comment by krig** [comment]
I pushed an alternative implementation purely in bash, however it is only tested for very simple cases. Also it is adapted from code found here: http://www.linuxquestions.org/questions/programming-9/bash-cidr-calculator-646701/ so the license situation is at best murky. ;)

**Comment by dmuhamedagic** [comment]
#! line is ignored in file which is sourced. Anyway, we cannot
change the shell, as not everybody uses bash.

**Comment by krig** [comment]
Hmm, well, then that idea won't work either since the code needs bash features like exponentiation and arithmetic for loops.

**Comment by kskmori** [comment]
> Is there a way to fix this without introducing a new program? @kskmori, Keisuke-san, you worked on a findif rewrite, any ideas?

I've commented on here:
https://github.com/ClusterLabs/resource-agents/issues/656#issuecomment-135323802

**Pull request closed without merging**
