### PR TITLE
Add gcp-pd-move python script

### PR DESCRIPTION
**Pull request by gut**

### CODE REVIEW

**Comment by gut** [comment]
I'm not really sure how to test the CSEK key. It looks to me that the file given should simply be read and handed over to google API but if somebody has some directions. I can gladly test.

A refactor of the python scripts scripts is something I'm willing to do next, as there is some common code copy-pasted.

**Comment by gut** [comment]
I'm not really sure how to test the CSEK key. It looks to me that the file given should simply be read and handed over to google API but if somebody has some directions. I can gladly test.

A refactor of the python scripts scripts is something I'm willing to do next, as there is some common code copy-pasted.

**Comment by krig** [comment]
Looks good to me.

**Comment by oalbrigt** [comment]
HOSTNAME and hostname should be changed to instacename equivalents.

**Comment by gut** [comment]
done

**Comment by oalbrigt** [comment]
ok to test

**Comment by oalbrigt** [comment]
Thanks.

**Pull request merged**
