### PR TITLE
managing "Secondary Private IP" for EC2 instances

### PR DESCRIPTION
**Pull request by guessi**
sample config:

    primitive res_awsvip ocf:heartbeat:awsvip \
        params awscli="/usr/local/bin/aws" \
        params secondary_private_ip="172.31.0.123"

Signed-off-by: guessi <guessi@gmail.com>

### CODE REVIEW

**Comment by krig** [comment]
Looks good to me! My only comment would be the `sleep 3` in the `start` and `stop` actions. Maybe this time should be configurable? But that can be added later if necessary.

**Comment by krig** [comment]
An option to sleeping might be to ping the assigned IP in a loop, something like

```
while [ . ]; do
    ping -nq -c 1 -W 1 ${SECONDARY_PRIVATE_IP} >/dev/null && break
    sleep 1
done
```

**Comment by guessi** [comment]
@krig 

I've thought about the `ping` trick, but it need to execute `ifconfig eth0:vip 1.2.3.4` to get IP address up,

btw, I would recommend to use with the RA `IPaddr2` together, with the rule of `order` and `colocation`.

**Comment by guessi** [comment]
@krig 

as for the `sleep 3`, I'll update later for making it configurable.

**Comment by krig** [comment]
Aha, I see how it works. That sounds good then.

**Comment by guessi** [comment]
@krig  please review it again, thanks

I will squash them into one when it is ready.

**Comment by krig** [comment]
Looks good!

**Comment by krig** [comment]
OK, merging these. Thanks!

**Pull request merged**
