### PR TITLE
SAPInstance: add systemd compatability

### PR DESCRIPTION
**Pull request by fmherschel**
SAPInstance: for systemd integrated sapstartsrv instances use systemd to check/start the service

### CODE REVIEW

**Comment by fmherschel** [comment]
Sorry for the fact the patch looks bigger as it really is - I also fixed some indents.

**Comment by oalbrigt** [comment]
Can you run `git rebase upstream/master` followed by `git push -f`?

That should solve the CI build issue.

**Comment by fmherschel** [comment]
@oalbrigt : I did rebase and pushed with force flag. Now the test is pending for round about 1 hour. Anything I still need to do?

**Comment by oalbrigt** [comment]
@fmherschel Thanks.

No, now we just need to wait for it to do it's thing (sometimes some nodes get stuck).

**Comment by oalbrigt** [comment]
LGTM. Thanks.

**Pull request merged**
