### PR TITLE
ocivip: Fix PRIMARY_IFACE variable. In some cases ip returns two lines

### PR DESCRIPTION
**Pull request by garutilorenzo**
Fix PRIMARY_IFACE variable. In some cases ip commands returns two lines

### CODE REVIEW

**Comment by oalbrigt** [comment]
Thanks.

**Comment by oalbrigt** [comment]
Can you give us an example of the 2 lines ip returns, so we might improve the patch or have an idea why it happens?

**Comment by garutilorenzo** [comment]
Hi @oalbrigt here one example

```
ubuntu@ubuntu-instance:~$ ip -4 route ls | grep default
default via 10.0.0.1 dev ens3 
default via 10.0.0.1 dev ens3 proto dhcp src 10.0.0.88 metric 100 
ubuntu@ubuntu-instance:~$
```  
OS version:
```  
ubuntu@ubuntu-instance:~$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Comment by oalbrigt** [comment]
Thanks. I dont see that issue on our distros, but I guess it could happen, and I can confirm that it shouldnt cause any harm.

**Pull request merged**
